Decoder:
  channel_factor: 64
  z_dim: 64
  upsample_s: [2, 1]
  upsample_t: [2, 1]
  spectral_norm: True

Encoder:
  res_type_encoder: 'resnet18'
  deterministic: false
  use_max_pool: false
  z_dim: 64
  channels: [64, 128, 256, 512, 512]
  stride_t: [1, 2, 2, 2]
  stride_s: [1, 2, 2, 2]

Discriminator_Temporal:
  eval_seq_length: 16
  res_type_encoder: 'resnet18'
  deterministic: false
  use_max_pool: true
  channels: [64, 64, 128, 256, 512]
  stride_t: [2, 2, 2, 2]
  stride_s: [1, 1, 2, 2]
  spectral_norm: True

Discriminator_Patch:
  in_channels: 3
  ndf: 64
  n_layers: 3
  use_actnorm: True
  spectral_norm: True

Training:
  patch_GAN: 'basic'
  GAN_Loss: 'hinge'
  w_coup_s: 1
  w_coup_t: 1
  w_fmap_t: 10
  w_percep: 30
  w_recon: 10
  w_GP: 10
  w_kl: 1e-5
  subsample_length: 12
  pretrain: 1
  n_epochs: 55
  lr: 2e-4
  workers: 20
  bs: 8
  bs_eval: 1
  verbose_idx: 30
  weight_decay: 1e-5
  lr_gamma: 0.98
  FVD: 'FVD'
  savename: '20230418'
  save_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage1_VAE/save/'
  reload_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage1_VAE/save/Stage1_BAIR_Date-2023-4-17-0-35-42_20230328'

Data:
  sequence_length: 17
  img_size: 64
  dataset: 'BAIR'
  reverse: False
  aug: True
  data_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/download_bair/'
  Augmentation:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0
    prob_hflip: 0.5

Logging:
  entity: '0d96660e1ccd97c40207a831c91de88b8763fa7b'
  project: "SWCD"
  mode: 'online'
