AE:
  deterministic: False
  in_size: 64
  norm: "in"
  encoder_type: "resnet50"
  use_actnorm_in_dec: False
  z_dim: 64

Discriminator_Patch:
  in_channels: 3
  ndf: 64
  n_layers: 3
  use_actnorm: True
  spectral_norm: True

Training:
  w_kl: 1e-5
  n_epochs: 60
  lr: 2e-4
  bs: 30
  weight_decay: 0
  workers: 30
  pretrain: 20
  savename: '20230328'
  save_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage2_VAE/saveAE/'

Data:
  sequence_length: 1
  img_size: 64
  dataset: 'BAIR'
  aug: True
  data_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/download_bair/'
  Augmentation:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
    prob_hflip: 0.5

Logging:
  entity: '0d96660e1ccd97c40207a831c91de88b8763fa7b'
  project: "SWCD"
  mode: 'online'

