Flow:
  n_flows: 20
  flow_hidden_depth: 2
  flow_mid_channels_factor: 8

Conditioning_Model:
  z_dim: 64
  checkpoint_name: 'encoder_stage2'
  model_name: 'Stage2_AE_BAIR_Date-2023-4-14-17-3-34_20230328'
  model_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage2_VAE/saveAE/'

First_stage_model:
  checkpoint_encoder: 'best_PFVD_ENC'
  checkpoint_decoder: 'best_PFVD_GEN'
  model_name: 'Stage1_BAIR_Date-2023-4-11-23-57-17_20230328'
  model_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage1_VAE/save/'

Training:
  n_epochs: 31
  lr: 1e-5
  workers: 30
  bs: 50
  bs_eval: 10
  control: False
  verbose_idx: 30
  weight_decay: 0
  gamma: 0.5
  step_size: 7
  beta1: 0.9
  beta2: 0.99
  amsgrad: True
  savename: '20230415'
  save_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage2_cINN/save/'
  reload_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/stage2_cINN/save/Stage2_BAIR_Date-2023-4-15-14-6-39_20230415'

Data:
  sequence_length: 17
  img_size: 64
  dataset: 'BAIR'
  aug: True
  data_path: '/data/gksruf293/swcd/image2video-synthesis-using-cINNs-main/download_bair/'
  Augmentation:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0
    prob_hflip: 0.5

Logging:
  entity: '0d96660e1ccd97c40207a831c91de88b8763fa7b'
  project: "SWCD"
  mode: 'online'